public enum ActionMergeType
{
	None,
	NoteDirectionChange,
	NotePreciseDirectionTweak,
	ArcHeadDirectionChange,
	ArcTailDirectionChange,
	ArcHeadMultTweak,
	ArcTailMultTweak,
	ChainSliceCountTweak,
	ChainSquishTweak,
	WallDurationTweak,
	WallLowerBoundTweak,
	WallUpperBoundTweak,
	EventMainTweak,
	EventAltTweak,
	BPMValueTweak,
	NJSValueTweak
}
